/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Pascal.java
 *
 * Created on Jan 6, 2012, 9:47:43 PM
 */
/**
 *
 * @author Giang
 */
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.*;
public class Pascal extends javax.swing.JFrame {

 /** Creates new form Pascal */
   public Pascal() {
      initComponents();      
   }

 /** This method is called from within the constructor to
  * initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is
  * always regenerated by the Form Editor.
  */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {
      panel1 = new java.awt.Panel();
      panel2 = new java.awt.Panel();
      panel3 = new java.awt.Panel();
   
      jTextField1 = new javax.swing.JTextField();
      jTextArea2 = new javax.swing.JTextArea();
      jLabel1 = new javax.swing.JLabel();
      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      jTextArea1 = new javax.swing.JTextArea();
      JFrame frame=new JFrame("PasCal Triangle");
      frame.setSize(1000,700);
      frame.setResizable(true);
      frame.setLocationRelativeTo(null);
   
   
      setEnabled(false);
   
      jTextField1.addActionListener(
            new java.awt.event.ActionListener() {
               @Override
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                  jTextField1ActionPerformed(evt);
               }
            
               private void jTextField1ActionPerformed(ActionEvent evt) {
                  throw new UnsupportedOperationException("Not yet implemented");
               }
            });
   
      jLabel1.setText("Show up to this rows:");
   
      jButton1.setText("do it");jButton1.addActionListener(
            new ActionListener()
            { 
               @Override
               public void actionPerformed(ActionEvent ae){
                  RandomFace.playSound("sounds/nextbutton.wav");
                  int rows=Integer.parseInt(jTextField1.getText());
                  if(rows < 0) 
                     return;
               //save the last row here
                  ArrayList<Double> last = new ArrayList<Double>();
                  last.add(1.0);
                  jTextArea1.append("0) ");
                  for(int a=0;a<rows;a++)
                  {jTextArea1.append(" ");}
                  jTextArea1.append(last.get(0)+"\n");
                  for(int i= 1;i <= rows;++i){
                  //work on the next row
                     ArrayList<Double> thisRow= new ArrayList<Double>();
                     thisRow.add(last.get(0)); //beginning
                     for(int j= 1;j < i;++j){//loop the number of elements in this row
                     //sum from the last row
                        thisRow.add(last.get(j - 1) + last.get(j));
                     }
                     thisRow.add(last.get(i-1)); //end
                     last= thisRow;//save this row
                     jTextArea1.append(i+") ");
                     for(int a=0;a<(rows-i);a++)
                     {jTextArea1.append(" ");}
                     for(int b=0;b<thisRow.size();b++)
                     {
                        jTextArea1.append(thisRow.get(b)+", ");
                        if(i==rows)
                        {jTextArea2.append("#"+(b+1)+") "+thisRow.get(b)+"\n");}
                     }
                     jTextArea1.append("\n");
                  }
                  
                  jTextArea2.append("Sum of row "+rows+" is "+Math.pow(2,rows)+"\n");
               }}
         );
   
      jButton2.setText("Clear ");jButton2.addActionListener(
            new ActionListener()
            { 
               @Override
               public void actionPerformed(ActionEvent ae){
                  RandomFace.playSound("sounds/clear.wav");
                  jTextArea1.setText("");
                  jTextArea2.setText("");
               }}
         );
      GroupLayout panel1Layout = new GroupLayout(panel1);
      panel1.setLayout(panel1Layout);
      panel1Layout.setAutoCreateContainerGaps(true);
      panel1Layout.setAutoCreateGaps(true);
      panel1Layout.setHorizontalGroup(panel1Layout.createSequentialGroup()
             .addComponent(jLabel1)
         	 .addGroup(panel1Layout.createParallelGroup(GroupLayout.Alignment.CENTER)
             .addComponent(jTextField1, GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
             .addComponent(jButton2, GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
             )
             .addGroup(panel1Layout.createParallelGroup(GroupLayout.Alignment.CENTER)
             .addComponent(jButton1, GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
         	             );
      panel1Layout.linkSize(SwingConstants.HORIZONTAL, jButton1, jButton2);
   
      panel1Layout.setVerticalGroup(panel1Layout.createSequentialGroup()
                 .addGroup(panel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                 .addComponent(jLabel1,GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                 .addComponent(jTextField1)
                 .addComponent(jButton1,GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
         	     .addComponent(jButton2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
             
         );
      GridLayout panel2Layout = new GridLayout();
      panel2.setLayout(panel2Layout);
      panel2.add(panel1);
      JScrollPane jScrollPane1=new javax.swing.JScrollPane(jTextArea2);
      jScrollPane1.setPreferredSize(panel1.getPreferredSize());
      panel2.add(jScrollPane1);
      jTextArea1.setEditable(false);
      jTextArea1.setSize(frame.getSize());       
      frame.getContentPane().add(panel2,BorderLayout.NORTH);
      frame.getContentPane().add(new javax.swing.JScrollPane(jTextArea1),BorderLayout.CENTER);
      frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE );
      frame.validate();
      frame.setVisible(true);
   
               
   }// </editor-fold>

 // Variables declaration - do not modify
   
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JTextArea jTextArea1;
   private javax.swing.JTextField jTextField1;
   private javax.swing.JTextArea jTextArea2;
   private java.awt.Panel panel1;
   private java.awt.Panel panel2;
   private java.awt.Panel panel3;

 // End of variables declaration
}
